// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

// Debug log
console.log("Controllers index loaded")

import AuthController from "./auth_controller"
application.register("auth", AuthController)

import BmiCalculatorController from "./bmi_calculator_controller"
console.log("BMI Controller imported:", BmiCalculatorController)

try {
  application.register("bmi-calculator", BmiCalculatorController)
  console.log("BMI Controller registered successfully")
} catch (error) {
  console.error("Error registering BMI Controller:", error)
}

import PregnancyCalculatorController from "./pregnancy_calculator_controller"
application.register("pregnancy-calculator", PregnancyCalculatorController)
